# Generated by Django 5.0 on 2023-12-28 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_usuario_profile_picture_alter_usuario_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20)),
                ('fase_funil', models.CharField(choices=[('prospeccao', 'Prospecção'), ('negociacao', 'Negociação')], max_length=100)),
                ('data_prevista_fechamento', models.DateField()),
                ('empresa_relacionada', models.CharField(max_length=100)),
                ('nome_contato', models.CharField(max_length=100)),
                ('telefone_contato', models.CharField(max_length=20)),
                ('email_contato', models.EmailField(max_length=254)),
                ('origem_lead', models.CharField(choices=[('site', 'Site'), ('telefone', 'Telefone')], max_length=100)),
                ('perfil_cliente', models.TextField()),
                ('numero_orcamento', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('historico_interacoes', models.TextField()),
                ('arquivos_anexados', models.FileField(upload_to='negociacoes/')),
                ('cargo_contato', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_produto_servico', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_cliente', models.CharField(blank=True, choices=[('vip', 'VIP'), ('regular', 'Regular')], max_length=50, null=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
